# Name of default conda environment for all tasks
conda_base_env: 'crispr-pipeline'

# Directory for input files
input: './input'

# Note the use of _R1_001.fastq.gz to ensure index files (*_I1_001.fastq.gz) are not matched
basename_regex: '*_R1_001.fastq.gz'
# Regex and pattern to define which fastqs to use and how to merge then
# For example, if you have the following fastq filestructure
#
# H90_CTR_HIGH_1_S4_L001_R1_001.fastq.gz
# H90_CTR_HIGH_1_S4_L002_R1_001.fastq.gz
# H90_CTR_HIGH_1_S4_L003_R1_001.fastq.gz
# H90_CTR_HIGH_1_S4_L004_R1_001.fastq.gz
# H90_CTR_HIGH_2_S13_L001_R1_001.fastq.gz
# H90_CTR_HIGH_2_S13_L002_R1_001.fastq.gz
# H90_CTR_HIGH_2_S13_L003_R1_001.fastq.gz
# H90_CTR_HIGH_2_S13_L004_R1_001.fastq.gz
# H90_CTR_LOW_1_S6_L001_R1_001.fastq.gz
# H90_CTR_LOW_1_S6_L002_R1_001.fastq.gz
# H90_CTR_LOW_1_S6_L003_R1_001.fastq.gz
# H90_CTR_LOW_1_S6_L004_R1_001.fastq.gz
# H90_CTR_LOW_2_S20_L001_R1_001.fastq.gz
# H90_CTR_LOW_2_S20_L002_R1_001.fastq.gz
# H90_CTR_LOW_2_S20_L003_R1_001.fastq.gz
# H90_CTR_LOW_2_S20_L004_R1_001.fastq.gz
# Undetermined_S0_L001_R1_001.fastq.gz
# Undetermined_S0_L002_R1_001.fastq.gz
# Undetermined_S0_L003_R1_001.fastq.gz
# Undetermined_S0_L004_R1_001.fastq.gz
#
# where the fastq name pattern is
# [sort_feature]_[condition]_[sort]_[technical_replicate]_[sample_ix]_[Lane]_R1_001.fastq.gz
# we can define a regex and pattern as shown with the default values to make sure
# all the 8 lanes for each technical replicate are collated together and the output
# file is prefixed with
# [sort_feature]_[condition]_[sort], e.g
# H90_CTR_HIGH
# H90_CTR_LOW
# Undetermined
#
# Note the use of (_\d+)*, e.g zero or more
fastq_regex: '(\S+?)(_\d+)*_S\d+_L00[1-4]_R1_001.fastq.gz'
# just keep the first group
fastq_pattern: '\1'



# filenames for references
reference:

  guides: './guides.csv'

bowtie:

  threads: 1

  options: '-v2 -l6 -m1'


resample:
  min: 0.05
  max: 3
  step: 0.05

mageck:
  # rra or mle
  method: 'rra'
  # comma-separated list of design files with design_{identifier}.txt naming convention
  # e.g designs: 'design_hs.txt,design_ctrl.txt'  
  designs: 'design_hs.txt,design_ctrl.txt'  
  mle_threads: 30
  mle_options: '--permutation-round 10 --remove-outliers '