# Name of default conda environment for all tasks
conda_base_env: 'crispr-pipeline'

# Directory for input files
input: './input'

# filenames for references
reference:

  guides: './guides.csv'

bowtie:

  threads: 1

  options: '-v2 -l6 -m1'